In [1]:
import pandas as pd 
import numpy as np

Write a function so that the columns of the output matrix are powers of the input
vector.

In [53]:
def vandermodematrix(l,n):
    l1 = []
    for i in l:
        for j in range(0,n):
            l1.append(pow(i,j))
    l2 = np.array(l1).reshape(-1,n)
    
    l3 = []
    for i in l:
        num = n
        for j in range(0,num):
            l3.append(pow(i,num-1))
            num=num-1
    l4 = np.array(l3).reshape(-1,n)
    
    return l2,l4
    
    
input_array = list(map(int,input("Enter the array element ---> ").strip().split(' ')))
col = int(input("Enter number of column ---> "))
incr,dcr = vandermodematrix(input_array,col)
print("Vandermode matrix in increasing power\n","-"*40,"\n" ,incr,"\n")
print("Vandermode matrix in decreasing power\n","-"*40,"\n" ,dcr)

Enter the array element ---> 1 2 3 4 5
Enter number of column ---> 5
Vandermode matrix in increasing power
 ---------------------------------------- 
 [[  1   1   1   1   1]
 [  1   2   4   8  16]
 [  1   3   9  27  81]
 [  1   4  16  64 256]
 [  1   5  25 125 625]] 

Vandermode matrix in decreasing power
 ---------------------------------------- 
 [[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]
 [625 125  25   5   1]]


Write a function to find moving average in an array over a window:
Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [15]:
def movingaverage(l,k):
    movingavg = len(l)-k+1
    for i in range(0,movingavg):
        sum_list = l[i:i+3]
        sum = np.sum(sum_list)
        print(f'y{i+1} ',round(sum/k,2))
        

l1= [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
k = 3
movingaverage(l1,k)

y1  5.0
y2  4.67
y3  5.67
y4  6.67
y5  9.67
y6  28.67
y7  49.33
y8  72.67
y9  84.0
y10  93.33
y11  116.33
